config/routes.rb
Gpki::Application.routes.draw do
  resources :nodes

  resources :leafs

end

app/models/leaf.rb
require 'digest/sha1'
# http://stackoverflow.com/questions/3393143/before-create-in-rails-model

class Leaf < ActiveRecord::Base
  attr_accessible :alt, :lat, :lon, :name
  
  before_create :set_hash
  before_update :set_hash
  
  def set_hash
    self.sha = Digest::SHA1.hexdigest "#{self.lat}/#{self.lon}/#{self.alt}/#{self.name}"
  end
end

app/models/node.rb
class Node < ActiveRecord::Base
  attr_accessible :l_child, :parent, :r_child, :sha
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/leafs_controller.rb
class LeafsController < ApplicationController
  # GET /leafs
  # GET /leafs.json
  def index
    @leafs = Leaf.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leafs }
    end
  end

  # GET /leafs/1
  # GET /leafs/1.json
  def show
    @leaf = Leaf.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @leaf }
    end
  end

  # GET /leafs/new
  # GET /leafs/new.json
  def new
    @leaf = Leaf.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @leaf }
    end
  end

  # GET /leafs/1/edit
  def edit
    @leaf = Leaf.find(params[:id])
  end

  # POST /leafs
  # POST /leafs.json
  def create
    @leaf = Leaf.new(params[:leaf])
  	
    respond_to do |format|
      if @leaf.save
        format.html { redirect_to @leaf, notice: 'Leaf was successfully created.' }
        format.json { render json: @leaf, status: :created, location: @leaf }
      else
        format.html { render action: "new" }
        format.json { render json: @leaf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leafs/1
  # PUT /leafs/1.json
  def update
    @leaf = Leaf.find(params[:id])

    respond_to do |format|
      if @leaf.update_attributes(params[:leaf])
        format.html { redirect_to @leaf, notice: 'Leaf was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @leaf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leafs/1
  # DELETE /leafs/1.json
  def destroy
    @leaf = Leaf.find(params[:id])
    @leaf.destroy

    respond_to do |format|
      format.html { redirect_to leafs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nodes }
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @node = Node.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/new
  # GET /nodes/new.json
  def new
    @node = Node.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    @node = Node.find(params[:id])
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(params[:node])

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render json: @node, status: :created, location: @node }
      else
        format.html { render action: "new" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.json
  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node = Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leafs_helper.rb
module LeafsHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gpki</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/leafs/_form.html.erb
<%= form_for(@leaf) do |f| %>
  <% if @leaf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leaf.errors.count, "error") %> prohibited this leaf from being saved:</h2>

      <ul>
      <% @leaf.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br />
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :alt %><br />
    <%= f.text_field :alt %>
  </div>
  <div class>
	
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leafs/edit.html.erb
<h1>Editing leaf</h1>

<%= render 'form' %>

<%= link_to 'Show', @leaf %> |
<%= link_to 'Back', leafs_path %>

app/views/leafs/index.html.erb
<h1>Listing leafs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Lat</th>
    <th>Lon</th>
    <th>Alt</th>
    <th>Sha</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @leafs.each do |leaf| %>
  <tr>
    <td><%= leaf.name %></td>
    <td><%= leaf.lat %></td>
    <td><%= leaf.lon %></td>
    <td><%= leaf.alt %></td>
    <td><%= leaf.sha %></td>
    <td><%= link_to 'Show', leaf %></td>
    <td><%= link_to 'Edit', edit_leaf_path(leaf) %></td>
    <td><%= link_to 'Destroy', leaf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Leaf', new_leaf_path %>

<h2>Geo-Coordinates</h2>
<table>
	<tr>
		<th>Building</th>
		<th>Latitude</th>
		<th>Longitude</th>
		<th>Altitude</th>
	</tr>
	<tr>
		<td>CMU-SV Building 23</td>
		<td>37.41014 - 37.41065    </td>
		<td>-122.05951 - -122.05999</td>
		<td>1</td>
	</tr>
	<tr>
		<td>CMU - SV Building 19</td>
		<td>37.41198 - 37.41256    </td>
		<td>-122.05907 - -122.05890</td>
		<td>1</td>
	</tr>
	<tr>
		<td>Post Office</td>
		<td>37.41207 - 37.41235    </td>
		<td>-122.05789 - -122.05769</td>
		<td>1</td>
	</tr>
	<tr>
		<td>Singularity</td>
		<td>37.41031 - 37.41085    </td>
		<td>-122.05868 - -122.05804</td>
		<td>1</td>
	</tr>
</table>  
	

app/views/leafs/new.html.erb
<h1>New leaf</h1>

<%= render 'form' %>

<%= link_to 'Back', leafs_path %>

app/views/leafs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @leaf.name %>
</p>

<p>
  <b>Lat:</b>
  <%= @leaf.lat %>
</p>

<p>
  <b>Lon:</b>
  <%= @leaf.lon %>
</p>

<p>
  <b>Alt:</b>
  <%= @leaf.alt %>
</p>

<p>
  <b>Sha:</b>
  <%= @leaf.sha %>
</p>


<%= link_to 'Edit', edit_leaf_path(@leaf) %> |
<%= link_to 'Back', leafs_path %>

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parent %><br />
    <%= f.number_field :parent %>
  </div>
  <div class="field">
    <%= f.label :l_child %><br />
    <%= f.number_field :l_child %>
  </div>
  <div class="field">
    <%= f.label :r_child %><br />
    <%= f.number_field :r_child %>
  </div>
  <div class="field">
    <%= f.label :sha %><br />
    <%= f.text_field :sha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<% require 'digest/sha1' %>
<% def trim_tree %>
	<% @nodes = Node.all %>
	<% @nodes.each do |node| %>
		<% node.destroy %>
	<% end %>
<% end %>

<h1>Merkle Hash Tree</h1>
<% if Node.all.length > 7 %> 
	<% trim_tree %>
<% end %>

<% sharr = [] #Array of Shas %>
<% narr2 = [] #array of nodes, level 2 %>
<% narr1 = [] #array of nodes, level 1 %>
<% narr0 = [] #array of nodes, level 0 %>

<% @leafs = Leaf.all %>

<%# for each leaf, make a node with that leaf's hash, make child Nil (these are the leaves) %>
<% @leafs.each do |leaf| %>

		<% sharr << leaf.sha %>
		<% @node = Node.new %>
		<% @node.sha = leaf.sha %>
		<% @node.l_child = nil %>
		<% @node.r_child = nil %>
		<% @node.save %>
		<% narr2 << @node %>
<%end %>
		<% @node.save %>
	
		<%# Now that leaves have begotten nodes, leaf nodes make parents %>
		<%# Divide nodes into left and right %>
	
		<% narr2.length.times do |i| %>
			<% if i % 2 != 0 %>
				<% narr1 << narr2[i] %>
			<% else %>
				<% narr1 << narr2[i] %>
			<% end %>
			<% if narr1[1] %>
				<%# create new parent node %>
				<% @node = Node.new %>
				<% @node.l_child = narr1[0].id %>
				<% @node.r_child = narr1[1].id %>
				<% @node.sha = Digest::SHA1.hexdigest "#{narr1[0].sha}/#{narr1[1].sha}" %>
				<% @node.save %>
				<%# Update children with new parent id %>
				<% narr1[0].parent = @node.id %>
				<% narr1[0].save %>
				<% narr1[1].parent = @node.id %>
				<% narr1[1].save %>
				<% narr1=[] %>
				<% narr0 << @node %>
				<%# Create Root %>
				<% if narr0[1] %>
				<% @node = Node.new %>
				<% @node.l_child = narr0[0].id %>
				<% @node.r_child = narr0[1].id %>
				<% @node.sha = Digest::SHA1.hexdigest "#{narr0[0].sha}/#{narr0[1].sha}" %>
				<% @node.save %>
				<% narr0[0].parent = @node.id %>
				<% narr0[0].save %>
				<% narr0[1].parent = @node.id %>
				<% narr0[1].save %>
				<% narr0=[] %>
				<% end %>
			<% end %>
		<% end %> 



<%# To manage tree.  Kludgy hack. %>


<table>
  <tr>
    <th>Parent</th>
    <th>L child</th>
    <th>R child</th>
    <th>Sha</th>
    <th>Position</th>
    <th></th>
    <th></th>
  </tr>

<% @nodes.each do |node| %>
  <tr>
    <td><%= node.parent %></td>
    <td><%= node.l_child %></td>
    <td><%= node.r_child %></td>
    <td><%= node.sha %></td>

    <td><%= link_to 'Show', node %></td>
    <td><%= link_to 'Edit', edit_node_path(node) %></td>
    <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Parent:</b>
  <%= @node.parent %>
</p>

<p>
  <b>L child:</b>
  <%= @node.l_child %>
</p>

<p>
  <b>R child:</b>
  <%= @node.r_child %>
</p>

<p>
  <b>Sha:</b>
  <%= @node.sha %>
</p>


<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>